sequenceDiagram
  participant participant_createKnipConfig as createKnipConfig
  participant participant_existsSync as existsSync
  participant participant_hasManagedExamplesEslintConfig as hasManagedExamplesEslintConfig
  participant participant_readFileSync as readFileSync
  participant_createKnipConfig->>participant_hasManagedExamplesEslintConfig: hasManagedExamplesEslintConfig()
  participant_hasManagedExamplesEslintConfig->>participant_existsSync: existsSync()
  participant_existsSync-->>participant_hasManagedExamplesEslintConfig: return
  participant_hasManagedExamplesEslintConfig->>participant_readFileSync: readFileSync()
  participant_readFileSync-->>participant_hasManagedExamplesEslintConfig: return
  participant_hasManagedExamplesEslintConfig-->>participant_createKnipConfig: return
