import { describe, expect, it } from 'bun:test';

import { getReadmeDocumentationErrors } from './readmeDocs.js';

describe('README documentation validation', () => {
  it('accepts a README that documents the canonical generated surface', () => {
    expect(getReadmeDocumentationErrors(createCanonicalReadmeFixture())).toEqual([]);
  });

  it('reports missing canonical usage references', () => {
    expect(getReadmeDocumentationErrors('ankh devtools --help')).toContain(
      'README.md is missing required documentation snippet: Standalone package ESLint configuration',
    );
  });
});

/*** Build one README fixture containing every required canonical documentation marker. */
function createCanonicalReadmeFixture(): string {
  return [
    '<!-- This file is generated by Paradox. Do not edit manually. -->',
    '# @ankhorage/devtools',
    '## Usage',
    'ankh devtools --help',
    'Standalone package ESLint configuration',
    'export default createConfig({',
    '## Generated documentation',
    'paradox/index.html',
  ].join('\n');
}
