const REQUIRED_README_SNIPPETS = [
  '<!-- This file is generated by Paradox. Do not edit manually. -->',
  '# @ankhorage/devtools',
  '## Usage',
  'ankh devtools --help',
  'Standalone package ESLint configuration',
  'export default createConfig({',
  '## Generated documentation',
  'paradox/index.html',
] as const;

export function getReadmeDocumentationErrors(readmeContents: string): string[] {
  return REQUIRED_README_SNIPPETS.flatMap((snippet) =>
    readmeContents.includes(snippet)
      ? []
      : [`README.md is missing required documentation snippet: ${snippet}`],
  );
}
